# Generated by Django 5.0.6 on 2024-11-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_folder_created_by'),
        ('project', '0016_alter_projectaisuggestions_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='allowed_users',
            field=models.ManyToManyField(
                blank=True, related_name='allowed_folders', to='project.membership'
            ),
        ),
        migrations.AlterField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='files',
                to='project.projectdetails',
            ),
        ),
    ]
