# Generated by Django 5.0.6 on 2024-12-09 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_clientprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        choices=[('Read', 'Read'), ('Write', 'Write'), ('Delete', 'Delete')],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        choices=[
                            ('Admin', 'Admin'),
                            ('Manager', 'Manager'),
                            ('Employee', 'Employee'),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    'permissions',
                    models.ManyToManyField(related_name='roles', to='client.permission'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employee_roles',
                        to='client.clientcompanyprofile',
                    ),
                ),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='roles',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employee_roles',
                        to='client.role',
                    ),
                ),
            ],
        ),
    ]
