# Generated by Django 5.1.3 on 2024-12-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_clientcompanyprofile_employee_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='company',
        ),
    ]
