# Generated by Django 5.0.6 on 2024-11-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_rename_timestamp_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
