# Generated by Django 5.1.3 on 2024-12-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_chatsession_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='Default Title', max_length=255, null=True),
        ),
    ]
