# Generated by Django 5.1.3 on 2025-01-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_chatmessage_user'),
        ('ai_assistant', '0008_alter_chatsession_title'),
    ]

    operations = []
