# Generated by Django 5.1.3 on 2024-11-21 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelManagers(
            name='messagemodel',
            managers=[],
        ),
        migrations.AlterField(
            model_name='dialogsmodel',
            name='user1',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='dialogs_as_user1',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='dialogsmodel',
            name='user2',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='dialogs_as_user2',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='received_messages',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='sender',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sent_messages',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Room Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'members',
                    models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='room',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages',
                to='inbox.roommodel',
            ),
        ),
    ]
