# Generated by Django 5.1.3 on 2025-01-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_messagemodel_options_and_more'),
        ('inbox', '0003_rename_content_inboxmessage_message'),
    ]

    operations = []
