# Generated by Django 5.1.3 on 2025-01-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_merge_20250121_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='inboxmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='InboxGroup',
        ),
        migrations.DeleteModel(
            name='InboxMessage',
        ),
    ]
