# Generated by Django 5.0.6 on 2024-10-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_crewrequirements_equipmentrequirements_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcrewrequirement',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='projectequipmentrequirement',
            name='equipment',
        ),
        migrations.AddField(
            model_name='projectcrewrequirement',
            name='crew_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='projectequipmentrequirement',
            name='equipment_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequirements',
            name='crew_requirements',
            field=models.ManyToManyField(
                related_name='projects_with_crew', to='project.projectcrewrequirement'
            ),
        ),
        migrations.AlterField(
            model_name='projectrequirements',
            name='equipment_requirements',
            field=models.ManyToManyField(
                related_name='projects_with_equipment', to='project.projectequipmentrequirement'
            ),
        ),
        migrations.DeleteModel(
            name='CrewRequirements',
        ),
        migrations.DeleteModel(
            name='EquipmentRequirements',
        ),
    ]
