# Generated by Django 5.1.3 on 2024-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_projectaisuggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaisuggestions',
            name='suggested_budget',
            field=models.TextField(blank=True, null=True),
        ),
    ]
