# Generated by Django 5.1.3 on 2024-11-22 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_projectaisuggestions_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaisuggestions',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='project.projectdetails'
            ),
        ),
    ]
