# Generated by Django 5.1.3 on 2024-12-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_projectaisuggestions_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='status',
            field=models.CharField(
                choices=[
                    ('PLANNING', 'Planning'),
                    ('IN_PROGRESS', 'In Progress'),
                    ('COMPLETED', 'Completed'),
                    ('CANCELLED', 'Cancelled'),
                    ('PAUSED', 'Paused'),
                    ('DEVELOPMENT', 'Development'),
                    ('PRE_PRODUCTION', 'Pre-Production'),
                    ('POST_PRODUCTION', 'Post-Production'),
                    ('RELEASED', 'Released'),
                ],
                default='PLANNING',
                max_length=30,
            ),
        ),
    ]
