# Generated by Django 5.1.3 on 2025-01-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_projectinvite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaisuggestions',
            name='suggested_crew',
            field=models.TextField(blank=True, null=True),
        ),
    ]
