# Generated by Django 5.1.3 on 2025-01-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_projectaisuggestions_suggested_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaisuggestions',
            name='sustainability_report',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Structured sustainability data in JSON format',
                null=True,
            ),
        ),
    ]
