# Generated by Django 5.1.3 on 2025-01-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_project_documents'),
        ('project', '0021_projectaisuggestions_suggested_crew'),
    ]

    operations = []
