# Generated by Django 5.1.3 on 2025-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_projectaisuggestions_sustainability_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='ai_context',
            field=models.JSONField(
                default=dict, help_text='Stores shared AI-generated context across reports'
            ),
        ),
    ]
