# Generated by Django 5.1.3 on 2025-01-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_projectdetails_ai_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaisuggestions',
            name='recommended_suppliers',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Structured supplier recommendations by location',
                null=True,
            ),
        ),
    ]
