# Generated by Django 5.1.3 on 2025-01-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_projectaisuggestions_recommended_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaisuggestions',
            name='recommended_suppliers',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Structured supplier recommendations by location',
                null=True,
            ),
        ),
    ]
