# Generated by Django 5.0.6 on 2024-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(
                blank=True, max_length=256, null=True, upload_to='profile_images/'
            ),
        ),
    ]
