# Generated by Django 5.1.3 on 2025-01-23 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_personalinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                (
                    'permissions',
                    models.ManyToManyField(
                        blank=True, related_name='tiers', to='accounts.permission'
                    ),
                ),
                (
                    'user_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tiers',
                        to='accounts.usertype',
                    ),
                ),
            ],
        ),
    ]
