# Generated by Django 5.1.3 on 2025-01-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
