# Generated by Django 5.0.6 on 2024-10-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_projectcrewrequirement_crew_and_more'),
        ('storyvord_calendar', '0004_event_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCalendar',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'project',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_calendar',
                        to='project.projectdetails',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'participants',
                    models.ManyToManyField(
                        blank=True, related_name='calendar_events', to='project.membership'
                    ),
                ),
                (
                    'calendar',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='calendar_events',
                        to='storyvord_calendar.projectcalendar',
                    ),
                ),
            ],
        ),
    ]
