# Generated by Django 5.0.6 on 2024-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyvord_calendar', '0007_remove_usercalendarevent_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalender',
            name='name',
            field=models.CharField(default='My Calendar', max_length=255),
        ),
    ]
