# Generated by Django 5.0.6 on 2024-11-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyvord_calendar', '0008_alter_usercalender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
