# Generated by Django 5.0.6 on 2024-11-30 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveConnection',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user_id_1',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='active_connections_1',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user_id_2',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='active_connections_2',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('user_id_1', 'user_id_2')},
            },
        ),
    ]
