# Generated by Django 5.0.6 on 2024-12-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0006_alter_callsheet_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='production_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
