# Generated by Django 5.1.3 on 2025-01-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0008_callsheet_allowed_users'),
        ('callsheets', '0008_calltime'),
    ]

    operations = []
