# Generated by Django 5.1.3 on 2025-01-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0009_merge_0008_callsheet_allowed_users_0008_calltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='lunch',
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('scene_number', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('cast', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('other_notes', models.TextField(blank=True, null=True)),
                (
                    'call_sheet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scenes',
                        to='callsheets.callsheet',
                    ),
                ),
            ],
        ),
    ]
