# Generated by Django 5.0.6 on 2024-12-17 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcompanytask',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='clientcompanytask',
            name='assigned_to',
            field=models.ManyToManyField(related_name='company_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
