# Generated by Django 5.0.6 on 2024-12-21 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_projectinvite_unique_together'),
        ('referral', '0003_clientinvitation_firstname_clientinvitation_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvitation',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='project.projectdetails'
            ),
        ),
    ]
