# Generated by Django 5.1.3 on 2024-12-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='scripts/'),
        ),
        migrations.AlterField(
            model_name='script',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
