# Generated by Django 5.1.3 on 2024-12-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creative_hub', '0003_script_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='file_url',
        ),
    ]
