# Generated by Django 5.1.3 on 2025-01-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_hub', '0004_remove_script_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='scene_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='script',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scenes',
                to='creative_hub.script',
            ),
        ),
    ]
